name: CI/CD Pipeline for Airbnb Management User Frontend

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/airbnb-management-user-frontend:${{ github.sha }} --build-arg VITE_GOOGLE_API_KEY='${{ secrets.VITE_GOOGLE_API_KEY }}' --build-arg VITE_LIVE_API_URL='${{ secrets.VITE_LIVE_API_URL }}' --build-arg VITE_LOCAL_API_URL='${{ secrets.VITE_LOCAL_API_URL }}' .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/airbnb-management-user-frontend:${{ github.sha }}

  deploy:
    name: Deploy to Server
    runs-on: self-hosted
    needs: build_and_push

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Step 0: Authorize Docker Hub to allow Docker Image Pull
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
            # Step 1: Pull the latest Docker image
            docker pull ${{ secrets.DOCKER_USERNAME }}/airbnb-management-user-frontend:${{ github.sha }}
      
            # Step 2: Stop and remove the existing container (if it exists)
            docker stop airbnb-management-user-frontend-container || true
            docker rm airbnb-management-user-frontend-container || true
            docker system prune -f 
            
            # Step 3: Run a new container with environment variables
            docker run -d \
              -p 5173:80 \
              --name airbnb-management-user-frontend-container \
              --restart unless-stopped \
              ${{ secrets.DOCKER_USERNAME }}/airbnb-management-user-frontend:${{ github.sha }}
      